"""
Django settings for CHF project.

Generated by 'django-admin startproject' using Django 1.9.1.

For more information on this file, see
https://docs.djangoproject.com/en/1.9/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.9/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.9/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '_fvs%!xbexbabfbvn4j6bb%7g4@*!mrem$3j553jqdss25xh&u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    
    'django.contrib.admin',
    'django_mako_plus.controller',
    'polymorphic',
    #'admin_tools',
    #'admin_tools.theming',
    #'admin_tools.menu',
    #'admin_tools.dashboard',
    #'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'homepage',
    'account',
    'catalog',
    
    'manager',
]

MIDDLEWARE_CLASSES = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    #'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    #'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_mako_plus.controller.router.RequestInitMiddleware',
]

ROOT_URLCONF = 'CHF.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                #'django.core.context_processors.request',
                #'admin_tools.template_loaders.Loader',
                
                
            ],
            
            
        },
    },
]

WSGI_APPLICATION = 'CHF.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.9/ref/settings/#databases

AUTH_USER_MODEL = 'account.User'

DATABASES = {
   'default': {
      'ENGINE': 'django.db.backends.postgresql_psycopg2',
      'NAME': 'CHF',
      'USER': 'postgres',
      'PASSWORD': 'focaccia',
      'HOST': 'localhost',
    }
#    'default': {
 #       'ENGINE': 'django.db.backends.sqlite3',
  #      'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
   # }
}


# Password validation
# https://docs.djangoproject.com/en/1.9/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

DEBUG_PROPAGATE_EXCEPTIONS = DEBUG  # never set this True on a live site
LOGGING = {
     'version': 1,
     'disable_existing_loggers': True,
     'formatters': {
         'simple': {
             'format': '%(levelname)s %(message)s'
         },
     },
     'handlers': {
         'console':{
             'level':'DEBUG',
             'class':'logging.StreamHandler',
             'formatter': 'simple'
         },
     },
     'loggers': {
         'django_mako_plus': {
             'handlers': ['console'],
             'level': 'DEBUG',
             'propagate': False,
         },
     },
 }



# Internationalization
# https://docs.djangoproject.com/en/1.9/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.9/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = (
     # SECURITY WARNING: this next line must be commented out at deployment
     BASE_DIR,  
 )
STATIC_ROOT = os.path.join(BASE_DIR, 'static')  

 ###############################################################
 ###   Specific settings for the Django-Mako-Plus app

DJANGO_MAKO_PLUS = {
     # identifies where the Mako template cache will be stored, relative to each app
     'TEMPLATES_CACHE_DIR': 'cached_templates',

     # the default app and page to render in Mako when the url is too short
     'DEFAULT_PAGE': 'index',
     'DEFAULT_APP': 'homepage',

     # the default encoding of template files
     'DEFAULT_TEMPLATE_ENCODING': 'utf-8',

     # these are included in every template by default - if you put your most-used libraries here, you won't have to import them exlicitly in templates
     'DEFAULT_TEMPLATE_IMPORTS': [
       'import os, os.path, re, json',
     ],

     # see the DMP online tutorial for information about this setting
     'URL_START_INDEX': 0,

     # whether to send the custom DMP signals -- set to False for a slight speed-up in router processing
     # determines whether DMP will send its custom signals during the process
     'SIGNALS': True,

     # whether to minify using rjsmin, rcssmin during 1) collection of static files, and 2) on the fly as .jsm and .cssm files are rendered
     # rjsmin and rcssmin are fast enough that doing it on the fly can be done without slowing requests down
     'MINIFY_JS_CSS': True,

     # see the DMP online tutorial for information about this setting
     'TEMPLATES_DIRS': [ 
       # '/var/somewhere/templates/',
     ],
 }
 
DEFAULT_TEMPLATE_IMPORTS = [
   'import os, os.path, re, datetime',
   'from decimal import Decimal',
 ]

 ###  End of settings for the Django-Mako-Plus
 ################################################################
